substitutions:
  filter_time: 5s
  filter_send_every: "1"
  filter_window_size: "3"

  can_tx_pin: GPIO2
  can_rx_pin: GPIO1

external_components:
  - source: github://yoziru/esphome-zehnder-comfoair@main
    components: [zehnder_comfoair_q]

packages:
  binary_sensors: github://yoziru/esphome-zehnder-comfoair/packages/binary_sensors.yml@main
  button: github://yoziru/esphome-zehnder-comfoair/packages/button.yml@main
  canbus: github://yoziru/esphome-zehnder-comfoair/packages/canbus.yml@main
  climate: github://yoziru/esphome-zehnder-comfoair/packages/climate.yml@main
  common: github://yoziru/esphome-zehnder-comfoair/packages/common.yml@main
  fan: github://yoziru/esphome-zehnder-comfoair/packages/fan.yml@main
  select: github://yoziru/esphome-zehnder-comfoair/packages/select.yml@main
  sensors: github://yoziru/esphome-zehnder-comfoair/packages/sensors.yml@main
  switch: github://yoziru/esphome-zehnder-comfoair/packages/switch.yml@main
  text_sensors: github://yoziru/esphome-zehnder-comfoair/packages/text_sensors.yml@main

esphome:
  name: zehnder-comfoair-q
  friendly_name: Zehnder ComfoAir Q

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB  
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO
  logs:
    canbus: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR API KEY"

ota:
  - platform: esphome
    password: "YOUR OTA KEY"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_rrm: true
  enable_btm: true

web_server:
  port: 80
  ota: false
  local: true

captive_portal:

# Board specific entities
# Output that blinks the LED
output:
  - platform: template
    id: status_output
    type: binary
    write_action:
      - if:
          condition:
            lambda: return (state);
          then:
            - light.turn_on:
                id: led
                brightness: 70%
                red: 100%
                green: 0%
                blue: 0%
          else:
            - light.turn_off: led

light:
  # Enable status LED
  - platform: status_led
    output: status_output
    name: "Status Led"
    entity_category: diagnostic

  #G35=RGB WS2812C-2020
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 35
    num_leds: 4
    chipset: ws2812
    id: led
    name: "Led"
    entity_category: diagnostic

#G41=Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms

# See docs: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md
zehnder_comfoair_q:
  id: comfoair
  request_ids:
    [
      16,
      49,
      54,
      55,
      65,
      66,
      67,
      81,
      82,
      117,
      118,
      119,
      120,
      121,
      122,
      128,
      129,
      130,
      192,
      209,
      210,
      211,
      212,
      212,
      213,
      214,
      215,
      216,
      217,
      218,
      220,
      221,
      225,
      227,
      274,
      275,
      276,
      277,
      278,
      290,
      291,
      292,
      293,
      294,
    ]